language: elixir
elixir:
  - 1.1.0
  - 1.1.1
otp_release:
  - 18.0
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
  - MIX_ENV=test mix do deps.get, compile, coveralls.travis
